// <auto-generated />

using AtendimentoAoCliente.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace AtendimentoAoCliente.Migrations
{
    [DbContext(typeof(AtendimentoDbContext))]
    partial class AtendimentoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("AtendimentoAoCliente.Modelos.Atendimentos", b =>
                {
                    b.Property<int>("AtendimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientesClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComentarioAtendente")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComentarioCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("SetoresSetorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusAtendimento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuariosUsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AtendimentoId");

                    b.HasIndex("ClientesClienteId");

                    b.HasIndex("SetoresSetorId");

                    b.HasIndex("UsuariosUsuarioId");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("AtendimentoAoCliente.Modelos.Clientes", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AtendimentoAoCliente.Modelos.Setores", b =>
                {
                    b.Property<int>("SetorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SetorId");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("AtendimentoAoCliente.Modelos.TipoUsuario", b =>
                {
                    b.Property<int>("TipoUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TipoUsuarioId");

                    b.ToTable("TipoUsuarios");
                });

            modelBuilder.Entity("AtendimentoAoCliente.Modelos.Usuarios", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SetorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsuarioAtivo")
                        .HasColumnType("INTEGER");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AtendimentoAoCliente.Modelos.Atendimentos", b =>
                {
                    b.HasOne("AtendimentoAoCliente.Modelos.Clientes", "Clientes")
                        .WithMany("Atendimento")
                        .HasForeignKey("ClientesClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtendimentoAoCliente.Modelos.Setores", "Setores")
                        .WithMany()
                        .HasForeignKey("SetoresSetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtendimentoAoCliente.Modelos.Usuarios", "Usuarios")
                        .WithMany("Atendimentos")
                        .HasForeignKey("UsuariosUsuarioId");

                    b.Navigation("Clientes");

                    b.Navigation("Setores");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AtendimentoAoCliente.Modelos.Clientes", b =>
                {
                    b.Navigation("Atendimento");
                });

            modelBuilder.Entity("AtendimentoAoCliente.Modelos.Usuarios", b =>
                {
                    b.Navigation("Atendimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
